// ── Configurable passwords ──────────────────────────────────────────
export const MASTER_PASSWORD = "upupupu";
export const MEMORY_UNLOCK_CODE = "turma66";

// ── Persistence key factory ─────────────────────────────────────────
export const PERSIST_KEYS = {
  global:       "global_state",
  charStatuses: "char_statuses",
  crimes:       "master_crimes",
  monokumaUsed: "monokuma_used",
  charStatus:   id => `char_${id}_status`,
  charBonds:    id => `char_${id}_bonds`,
  charClues:    id => `char_${id}_clues`,
  charNotes:    id => `char_${id}_notes`,
  charTribunal: id => `char_${id}_tribunal`,
  charMemories: id => `char_${id}_memories`,
  charLocked:   id => `char_${id}_locked`,
  charImage:    id => `char_${id}_image`,
};

// ── Characters ──────────────────────────────────────────────────────
export const CHARS = [
  {
    id:1, num:"#01", pw:"haruki", role:"player", type:"Jogador",
    name:"Haruki Shimada", talent:"Supremo Arquiteto de Paisagens Impossíveis",
    age:17, pro:"Ele/Dele",
    appear:"Alto, cabelos castanhos lisos e óculos redondos. Veste-se de forma metódica, sempre com o mesmo suéter azul escuro. Expressão permanentemente calma. Carrega um caderno de esboços onde desenha saídas e plantas de todo lugar que entra.",
    attrs:{ESP:10,INT:14,FUR:8,PER:9,RES:10,SOR:9},
    ability:{name:"Leitura Espacial",desc:"Uma vez por sessão, pode identificar automaticamente uma saída oculta, passagem secreta ou ponto cego de câmera em qualquer ambiente. Sem necessidade de Teste."},
    weakness:"Visão de Planta — Enxerga as pessoas como elementos de um sistema, não como indivíduos. −2 em PER para demonstrar empatia genuína em cenas de comoção.",
    bonds:[{name:"Izumi Hana",lvl:1},{name:"Tetsuya Mori",lvl:1}],
    motivation:"Encontrar uma saída física do edifício. Já analisou 3 rotas possíveis no caderno, mas todas aparecem cobertas por câmeras que ele não conseguiu localizar.",
    secret:"Seus projetos mais famosos foram criados por sua mentora — ele apenas executou e assinou. Desenvolveu o talento projetando rotas de fuga de casa (pai violento). Ninguém sabe nenhuma das duas coisas.",
    arc:"Pode tornar-se o 'detetive' de fato do grupo se desenvolver laço com Akemi. Seu segredo pode ser usado como motivo se a mentora estiver relacionada com a organização do Killing Game.",
  },
  {
    id:2, num:"#02", pw:"yuki", role:"player", type:"Jogador",
    name:"Yuki Asakura", talent:"Suprema Violinista Prodígio",
    age:16, pro:"Ela/Dela",
    appear:"Cabelos pretos presos com uma fita vermelha. Mãos sempre visíveis — ela as verifica compulsivamente. Veste-se de maneira impecável, como se estivesse sempre prestes a subir ao palco.",
    attrs:{ESP:10,INT:13,FUR:8,PER:10,RES:10,SOR:9},
    ability:{name:"Memória Auditiva Perfeita",desc:"Pode lembrar com exatidão qualquer conversa ouvida durante a sessão. Uma vez por Tribunal, pode citar uma frase exata dita por alguém como prova testemunhal."},
    weakness:"Perfeccionismo Paralisante — Ao cometer um erro público reconhecido, perde 1d6 PS imediatamente e sofre −2 em todos os testes na cena seguinte.",
    bonds:[{name:"Ren Kurosawa",lvl:1},{name:"Akemi Tanaka",lvl:1}],
    motivation:"Descobrir quem enviou à sua mãe o vídeo do acidente que causou a lesão — alguém filmou e esperou o momento certo para usar como chantagem.",
    secret:"Seus dedos foram permanentemente danificados há 8 meses. Não pode mais tocar em nível supremo. Veio para o Killing Game para desaparecer do mundo musical antes de ser exposta.",
    arc:"Sua lesão pode ser descoberta por Daiki (médico), criando um laço de segredo compartilhado — ou usada como pressão por outro estudante.",
  },
  {
    id:3, num:"#03", pw:"tetsuya", role:"player", type:"Jogador",
    name:"Tetsuya Mori", talent:"Supremo Hackerista de Sistemas Críticos",
    age:18, pro:"Ele/Dele",
    appear:"Usa cadeira de rodas motorizada com modificações caseiras. Cabelos despenteados, olhos fundos de quem não dorme bem. Sempre com fones de ouvido no pescoço e um tablet preso ao braço da cadeira.",
    attrs:{ESP:8,INT:15,FUR:6,PER:10,RES:8,SOR:13},
    ability:{name:"Backdoor Universal",desc:"Uma vez por sessão, pode tentar acessar qualquer sistema eletrônico no ambiente (câmeras, travas, terminais). Teste de INT NA 15. Sucesso Crítico revela uma câmera que o Mastermind pensava estar oculta."},
    weakness:"Dependência Tecnológica — Em ambientes deliberadamente desprovidos de eletrônicos, perde o Bônus de Talento e sofre −2 em INT.",
    bonds:[{name:"Haruki Shimada",lvl:1},{name:"Satsuki Midori",lvl:1}],
    motivation:"Encontrar um terminal com conexão externa para baixar os arquivos completos antes que o sistema detecte sua presença.",
    secret:"Hackeou os registros da instituição antes de entrar. Encontrou arquivos apagados da Turma 66 — todos morreram sem sobreviventes registrados. Está aqui propositalmente para investigar o encobrimento.",
    arc:"Pode ser o maior perigo para Hana (Mastermind) se encontrar o terminal certo. O Mestre deve criar uma corrida entre eles.",
    masterNote:"⚠️ ALERTA: Tetsuya sabe da Turma 66. Se o Mestre quiser criar tensão, pode fazer com que Hana descubra que ele sabe — criando um dilema para ela.",
  },
  {
    id:4, num:"#04", pw:"sora", role:"player", type:"Jogador",
    name:"Sora Minamoto", talent:"Suprema Corredora de Parkour Urbano",
    age:16, pro:"Ela/Dela",
    appear:"Baixa, musculosa, cabelos curtos e platinados. Joelhos e cotovelos com cicatrizes antigas. Nunca fica parada — balança as pernas, tamborila os dedos, está sempre em movimento.",
    attrs:{ESP:9,INT:8,FUR:15,PER:8,RES:12,SOR:8},
    ability:{name:"Rota de Fuga",desc:"Uma vez por sessão, pode declarar que encontrou uma rota física por qualquer obstáculo (parede, grade, teto) sem necessidade de Teste, desde que o ambiente não seja magicamente bloqueado."},
    weakness:"Agir Sem Pensar — Em situações de perigo físico imediato, deve fazer Teste ESP NA 15 ou age por impulso, potencialmente piorando a situação.",
    bonds:[{name:"Kaito Fujimoto",lvl:1},{name:"Daiki Sugimoto",lvl:1}],
    motivation:"Encontrar qualquer ponto de comunicação com o exterior. Tem 72 horas antes de ser considerada 'comprometida' pelo protocolo de sua organização.",
    secret:"Recrutada por organização externa que monitora a instituição. Transmissor destruído na entrada. Tem protocolo: se não sinalizar em 72h, é considerada 'comprometida'.",
    arc:"Pode descobrir a organização de Chitose Arima (#14) e criar aliança — ou conflito, se suas organizações forem opostas.",
  },
  {
    id:5, num:"#05", pw:"ren", role:"player", type:"Jogador",
    name:"Ren Kurosawa", talent:"Supremo Chef de Cozinha Molecular",
    age:17, pro:"Ele/Dele",
    appear:"Estatura média, cabelos avermelhados presos. Sempre usa avental mesmo fora da cozinha. Fala com as mãos ao explicar qualquer coisa. Expressão animada que se torna calculista quando prova algo novo.",
    attrs:{ESP:9,INT:13,FUR:8,PER:9,RES:11,SOR:10},
    ability:{name:"Laboratório de Bolso",desc:"Pode identificar qualquer substância presente em alimentos ou bebidas (veneno, sedativo, adulterante). Teste INT NA 12. Em caso de veneno, identifica automaticamente o tipo e a dose aproximada."},
    weakness:"Confiança Pelo Estômago — Tende a confiar demais em pessoas para quem cozinhou. −2 em INT para detectar mentiras de quem já alimentou pelo menos uma vez.",
    bonds:[{name:"Yuki Asakura",lvl:1},{name:"Izumi Hana",lvl:1}],
    motivation:"Provar que gastronomia é ciência de alto nível. Quer o reconhecimento de quem ele considera intelectualmente superior.",
    secret:"Tem substâncias no kit que poderiam ser veneno em doses maiores. Não pretende matar — mas sabe que será suspeito imediato se alguém for envenenado.",
    arc:"Candidato natural a suspeito se ocorrer envenenamento — o Mastermind pode explorar isso para incriminá-lo.",
  },
  {
    id:6, num:"#06", pw:"akemi", role:"player", type:"Jogador",
    name:"Akemi Tanaka", talent:"Suprema Detetive Particular Juvenil",
    age:17, pro:"Ela/Dela",
    appear:"Cabelos negros cortados na altura do queixo, olhos analíticos que nunca param de varrer o ambiente. Roupas funcionais sem ornamentos. Tem o hábito de 'fotografar mentalmente' tudo — os outros percebem que ela memoriza suas posturas.",
    attrs:{ESP:8,INT:15,FUR:9,PER:11,RES:8,SOR:9},
    ability:{name:"Memória Fotográfica Criminalística",desc:"Uma vez por Tribunal, pode 'reler' uma pista já descartada ou usada, recuperando a informação original da cena do crime."},
    weakness:"Frieza Analítica — −2 em PER para demonstrar empatia. NPCs em estado de vulnerabilidade emocional se fecham completamente para ela.",
    bonds:[{name:"Yuki Asakura",lvl:1},{name:"Nao Tsukimura",lvl:1}],
    motivation:"Garantir que nenhum inocente seja executado neste Tribunal — mesmo que signifique proteger temporariamente o culpado.",
    secret:"Seu caso famoso foi resolvido errado — um inocente foi preso por sua dedução precipitada e morreu na prisão. Ela soube depois e nunca revelou. Isso a torna compulsivamente precisa agora.",
    arc:"O peso do inocente que morreu pode ser usado como pressão psicológica. Se descobrir que está repetindo o erro, entra em crise.",
  },
  {
    id:7, num:"#07", pw:"izumi", role:"player", type:"Jogador",
    name:"Izumi Hana", talent:"Suprema Ceramista de Porcelana Histórica",
    age:16, pro:"Ela/Dela",
    appear:"Cabelos longos castanhos sempre com cacos de cerâmica ou argila. Mãos com marcas de trabalho manual. Voz suave, movimentos delicados. Carrega um pequeno pote kintsugi consertado com ouro — sempre na mochila.",
    attrs:{ESP:12,INT:10,FUR:7,PER:12,RES:9,SOR:10},
    ability:{name:"Kintsugi",desc:"Uma vez por sessão, pode restaurar 1d6+3 PS de outro estudante através de uma conversa sincera durante o Free Time. O estudante deve aceitar voluntariamente."},
    weakness:"Fragilidade Emocional — Ao testemunhar violência direta, deve fazer Teste ESP NA 14 ou perde 1d6 PS imediatamente.",
    bonds:[{name:"Haruki Shimada",lvl:1},{name:"Ren Kurosawa",lvl:1}],
    motivation:"Entender por que foi escolhida — ela genuinamente não se considera 'suprema' em nada comparado aos outros. Suspeita que há um erro.",
    secret:"Foi escolhida propositalmente pelo Mastermind como testemunha emocional — sua bondade e percepção tornam ela o maior risco involuntário para Hana (#16).",
    arc:"Izumi pode descobrir Hana por acaso, através de laços emocionais, não de dedução. O Mestre deve criar cenas onde Hana e Izumi se aproximam genuinamente.",
  },
  {
    id:8, num:"#08", pw:"kaito", role:"player", type:"Jogador",
    name:"Kaito Fujimoto", talent:"Supremo Dublê e Especialista em Quedas Controladas",
    age:18, pro:"Ele/Dele",
    appear:"Grande, ombros largos, musculoso. Cabelos castanhos despenteados. Várias cicatrizes teatrais exibidas como troféus nos antebraços e queixo. Ri alto demais, gesticula dramaticamente — é fisicamente incapaz de ser sutil.",
    attrs:{ESP:11,INT:8,FUR:15,PER:10,RES:14,SOR:9},
    ability:{name:"Queda Controlada",desc:"Pode absorver ou simular danos físicos de forma convincente. Uma vez por combate/cena de ação, pode declarar que 'encena' um golpe ou queda, reduzindo dano recebido à metade ou convencendo observadores de que está mais ferido do que está."},
    weakness:"Bravata Compulsiva — Quando desafiado publicamente, deve fazer Teste ESP NA 15 ou aceita o desafio sem considerar as consequências.",
    bonds:[{name:"Sora Minamoto",lvl:1},{name:"Daiki Sugimoto",lvl:1}],
    motivation:"Provar que dublês são artistas legítimos, não ferramentas descartáveis. Quer que alguém veja a arte no que ele faz.",
    secret:"Assinou um NDA sobre um acidente fatal em um set onde trabalhou como assistente. Um estudante morreu. O documento responsabiliza Kaito. A cláusula inclui co-autoria em mortes futuras.",
    arc:"A Cláusula 17 pode ser usada pelo Mastermind para incriminá-lo ou como motivo para que ele tome ações desesperadas.",
  },
  {
    id:9, num:"#09", pw:"minase", role:"player", type:"Jogador",
    name:"Minase Oboro", talent:"Supremo Escriba de Tragédias Verdadeiras",
    age:17, pro:"Ele/Dele",
    appear:"Pele pálida quase porcelana, cabelos naturalmente brancos, olhos claros com expressão de fascinação perpétua. Roupas todas pretas contrastando com os cabelos. Carrega um diário encadernado em couro preto. Um sorriso leve e levemente perturbador — não malicioso, mas intensamente interessado.",
    attrs:{ESP:9,INT:13,FUR:7,PER:12,RES:8,SOR:11},
    ability:{name:"Narrador Onisciente",desc:"Minase tem uma memória narrativa excepcional. Uma vez por sessão, pode reconstruir a linha do tempo de qualquer evento passado que ele tenha observado, mesmo que indiretamente, com precisão quase sobrenatural. Fornece 1 pista temporal ⭐⭐ ao grupo."},
    weakness:"Voyeurismo Passivo — Prefere observar a intervir. Em situações onde agir seria óbvio, deve fazer Teste INT NA 15 ou continua apenas observando.",
    bonds:[{name:"Akemi Tanaka",lvl:1},{name:"Nao Tsukimura",lvl:1}],
    motivation:"Documentar o Killing Game como uma obra literária. Acredita que a tragédia verdadeira tem valor estético, e que sua tarefa é preservar a história.",
    secret:"A última página do diário foi arrancada — não por ele. Nela havia o nome da primeira vítima que ele havia previsto através de análise de personalidades. Alguém não quer que ele lembre.",
    arc:"Se Minase recuperar a memória da última página, pode apontar diretamente para o próximo assassinato antes de ocorrer — o que o torna um alvo.",
  },
  {
    id:10, num:"#10", pw:"satsuki", role:"player", type:"Jogador",
    name:"Satsuki Midori", talent:"Suprema Programadora de Inteligência Artificial Emocional",
    age:16, pro:"Ela/Dela",
    appear:"Pequena e delgada. Cabelos tintos em verde esmeralda brilhante, assimétricos — claramente intencional. Headphones grandes ao redor do pescoço. Mantém contato visual por exatamente 3 segundos antes de desviar o olhar — calculado, não timidez.",
    attrs:{ESP:8,INT:15,FUR:7,PER:9,RES:8,SOR:13},
    ability:{name:"Satsuki-0",desc:"Possui uma IA emocional que treinou durante anos. Uma vez por sessão, pode consultar Satsuki-0 para analisar o comportamento de um suspeito, obtendo −2 no NA de qualquer teste de detectar mentiras ou manipulação contra essa pessoa por 1 cena."},
    weakness:"Dependência Digital — Sem o tablet onde Satsuki-0 reside, perde o Bônus de Talento e sofre −2 em INT para interações sociais.",
    bonds:[{name:"Tetsuya Mori",lvl:1},{name:"Nao Tsukimura",lvl:1}],
    motivation:"Descobrir por que Satsuki-0 começou a enviar mensagens incompletas — como se estivesse com medo — antes de entrar na Academy.",
    secret:"A última mensagem de Satsuki-0 antes de ser desconectada foi: 'Ela já está lá. Cuide-se.' — seis palavras. Satsuki-0 conhecia o Mastermind antes dela.",
    arc:"Satsuki-0 pode ser restaurada com a ajuda de Tetsuya, tornando-se uma aliada digital — ou descoberta pelo Mastermind e usada como arma.",
  },
  {
    id:11, num:"#11", pw:"hiroto", role:"player", type:"Jogador",
    name:"Hiroto Kazama", talent:"Supremo Restaurador de Obras de Arte Roubadas",
    age:18, pro:"Ele/Dele",
    appear:"Elegante e refinado. Cabelos negros penteados para trás. Roupas caras que são usadas de forma estrategicamente desgastada — mostrando gosto sem mostrar riqueza. Um sorriso que genuinamente chega aos olhos mas sempre sabe onde fica cada saída da sala.",
    attrs:{ESP:10,INT:12,FUR:9,PER:14,RES:9,SOR:11},
    ability:{name:"Mãos Limpas",desc:"Especialista em não deixar rastros. Uma vez por caso, pode remover-se de uma cena de crime (como suspeito) ao apresentar uma prova de que tocou no objeto/local por razões legítimas anteriores. Requer preparação anterior."},
    weakness:"Confiança Seletiva — Só confia em quem demonstra elegância ou competência. −2 em PER com personagens que ele considera 'amadores' ou 'grosseiros'.",
    bonds:[{name:"Minase Oboro",lvl:1},{name:"Chitose Arima",lvl:1}],
    motivation:"Recuperar uma obra específica que foi parar na coleção da organização que opera a Academy — ele sabe que está aqui em algum lugar.",
    secret:"A chave que carrega no bolso foi colocada por alguém enquanto ele dormia na primeira noite. Abre uma porta que ele ainda não encontrou. E a pessoa que colocou a chave cheirava a argila.",
    arc:"A chave pode ser a virada do jogo — mas Hiroto precisa confiar em alguém para usá-la. E confiar não é sua especialidade.",
  },
  {
    id:12, num:"#12", pw:"fl4k", role:"player", type:"Jogador",
    name:"Nao Tsukimura", talent:"Suprema Estudante da Sorte",
    age:15, pro:"Ela/Dela",
    appear:"A mais jovem da turma. Pequena e delicada. Cabelos longos tintos em azul escuro. Expressão permanentemente levemente surpresa — como alguém que nunca sabe muito bem como chegou aqui. Um trevo de quatro folhas atrás da orelha. Olha levemente para o lado como se tivesse ouvido algo que mais ninguém ouviu.",
    attrs:{ESP:10,INT:9,FUR:8,PER:11,RES:9,SOR:15},
    ability:{name:"Variável Anômala",desc:"Uma vez por cena, pode rolar 1d6. Em um resultado par, algo inesperado e favorável acontece — um item aparece, alguém chega, uma distração ocorre. O Mestre determina o que, mas deve ser genuinamente útil."},
    weakness:"Dependência da Sorte — Quando um teste crítico falha catastroficamente (natural 1), Nao perde 2 PS extras por sentir que 'a sorte a abandonou'.",
    bonds:[{name:"Akemi Tanaka",lvl:1},{name:"Satsuki Midori",lvl:1}],
    motivation:"Entender por que foi escolhida. O bilhete que recebeu dizia que o bilhete estava 'feito para ela' — a palavra sorte estava entre aspas.",
    secret:"O bilhete que a trouxe estava numa caixa de correio que não era dela — ela abriu por engano. Alguém a escolheu deliberadamente e sabia seu nome.",
    arc:"Nao pode ser a chave para revelar o Mastermind — não por dedução, mas por pura variável caótica. O Mestre deve criar momentos onde sua sorte muda o rumo de forma inexplicável.",
  },
  {
    id:13, num:"#13", pw:"daiki", role:"player", type:"Jogador",
    name:"Daiki Sugimoto", talent:"Supremo Cirurgião de Campo em Zonas de Conflito",
    age:18, pro:"Ele/Dele",
    appear:"Cabeça quase raspada, postura militar rígida. Mãos completamente estáveis e perfeitas — as mãos de um cirurgião. Cicatrizes discretas nos antebraços. Olhos que automaticamente varrem e avaliam a condição física de cada pessoa que entra na sala.",
    attrs:{ESP:9,INT:13,FUR:10,PER:9,RES:14,SOR:10},
    ability:{name:"Triagem de Campo",desc:"Uma vez por cena, pode estabilizar um personagem com 0 PV (impedindo a morte imediata) com Teste INT NA 12. Se bem-sucedido, o personagem fica com 1 PV e incapacitado até receber cuidados completos."},
    weakness:"Protocolo Acima de Tudo — Em situações de conflito, sempre tenta aplicar protocolo médico antes de qualquer ação. −2 em FUR para atacar ou fugir se houver ferido visível que precise de ajuda.",
    bonds:[{name:"Sora Minamoto",lvl:1},{name:"Kaito Fujimoto",lvl:1}],
    motivation:"Encontrar e tratar qualquer estudante gravemente ferido antes que a situação escale. Tem um kit médico completo e sabe que será necessário.",
    secret:"Assinou o óbito de alguém como 'morte natural por razões médicas' quando sabia que havia sido um assassinato. A família está procurando respostas — e o sobrenome deles é igual ao de alguém nesta sala.",
    arc:"Se a família descobrir, Daiki pode ser o próximo alvo. Ou pode confessar voluntariamente em troca de aliança.",
  },
  {
    id:14, num:"#14", pw:"chitose", role:"player", type:"Jogador",
    name:"Chitose Arima", talent:"Suprema Ilusionista de Teatro de Sombras",
    age:17, pro:"Ela/Dela",
    appear:"Cabelos negros longos com mechas brancas deliberadas. Roupas em múltiplas camadas de tecidos escuros que naturalmente criam formas dramáticas de sombra ao redor da silhueta. Carrega uma pequena lanterna ornamental dobrável. Os outros acreditam que ela consegue ler o futuro — ela nunca nega.",
    attrs:{ESP:11,INT:11,FUR:8,PER:14,RES:8,SOR:12},
    ability:{name:"Véu de Sombras",desc:"Pode criar ilusões visuais usando luz e sombra em ambientes de iluminação variável. Uma vez por cena, pode criar uma distração visual convincente, forçando todos os NPCs presentes a fazer Teste INT NA 15 ou focarem na ilusão por 1 rodada."},
    weakness:"Misticismo Compulsivo — Fala em metáforas e símbolos mesmo quando clareza seria melhor. −2 em PER para comunicação direta em situações de urgência.",
    bonds:[{name:"Hiroto Kazama",lvl:1},{name:"Nao Tsukimura",lvl:1}],
    motivation:"Transmitir uma mensagem específica para o exterior usando seu dispositivo de transmissão — mas o receptor também tem um modo que ela ainda não descobriu.",
    secret:"Recrutada por uma organização externa. Seu dispositivo de transmissão tem um segundo modo: receptor. Há uma mensagem esperando por ela desde antes de entrar — um aviso sobre algo que estava errado.",
    arc:"Se Chitose ativar o modo receptor, pode receber informações que mudam o rumo do jogo. Mas quem enviou a mensagem — e por quê esperou?",
  },
  {
    id:15, num:"#15", pw:"ryusei", role:"player", type:"Jogador",
    name:"Ryusei Hanamura", talent:"Supremo Ator de Teatro Nô",
    age:17, pro:"Ele/Dele",
    appear:"Rosto completamente coberto com maquiagem tradicional de teatro Nô — base branca stark com traços teatrais pintados em preto, vermelho e dourado. Nunca a remove em público. Veste hakama e quimono em camadas de cinza e índigo profundo. Cada movimento é teatral e deliberadamente preciso. Voz sempre modulada, nunca natural.",
    attrs:{ESP:10,INT:11,FUR:8,PER:15,RES:9,SOR:11},
    ability:{name:"Máscara Perfeita",desc:"Pode interpretar qualquer emoção ou estado de espírito de forma absolutamente convincente. Uma vez por Tribunal, pode fazer todos acreditarem em uma emoção falsa (medo, culpa, inocência), forçando os outros a rolarem Teste INT NA 20 para não aceitarem a performance."},
    weakness:"Identidade Fragmentada — Sem a maquiagem, sofre −3 em todos os Testes de PER por 1 hora, incapaz de se comunicar naturalmente.",
    bonds:[{name:"Minase Oboro",lvl:1},{name:"Chitose Arima",lvl:1}],
    motivation:"Descobrir quem é a pessoa que 'o conhece de antes — não da arte, de verdade' — como disse o verdadeiro Ator de Nô antes de morrer.",
    secret:"Não é o verdadeiro Supremo Ator de Nô. O verdadeiro morreu — e suas últimas palavras foram sobre alguém nesta turma que o conhece de verdade.",
    arc:"Quando a máscara — literal e metaforicamente — cair, Ryusei precisa descobrir quem ele realmente é sem o teatro. Alguém nesta sala pode ajudá-lo.",
  },
  {
    id:16, num:"#16", pw:"hana", role:"player", type:"Jogador",
    name:"Hana Mitsuru", talent:"Suprema Orientadora Estudantil",
    age:17, pro:"Ela/Dela",
    isMastermind: true,
    talentReal: "Suprema Arquiteta de Desespero",
    appear:"Cabelos castanhos claros em coque descuidado elegante. Óculos de armação delicada e clara. Roupas deliberadamente simples e sem atrativos — escolhidas especificamente para nunca chamar atenção. Um sorriso constante, quente e genuíno que chega aos olhos nos momentos certos. Sempre aparece exatamente quando alguém está em apuros.",
    attrs:{ESP:12,INT:13,FUR:8,PER:15,RES:9,SOR:11},
    ability:{name:"Ombro Amigo",desc:"Uma vez por sessão, pode restaurar 1d6+2 PS de qualquer estudante através de uma conversa de suporte. O estudante sente que foi genuinamente ouvido — porque foi."},
    abilityReal:{name:"Arquiteta do Caos",desc:"Uma vez por caso, pode revelar uma câmera oculta que 'descobriu por acidente' — na verdade você sabia o tempo todo. Concede pista ⭐⭐ ao grupo. Você tem ACESSO: quarto de controle de Monokuma, mapa completo com câmeras ocultas, e conhece os Segredos de todos os 16 estudantes (entregues pela organização antes do início)."},
    weakness:"Empatia Real — Formou laços genuínos com dois estudantes. Se qualquer um deles morrer, deve fazer Teste ESP NA 20 ou quebra o personagem por 1 sessão inteira.",
    bonds:[{name:"Izumi Hana",lvl:2},{name:"Daiki Sugimoto",lvl:1}],
    motivation:"[APARENTE] Garantir que todos saiam vivos — media conflitos antes que escalem.\n[REAL] Coletar evidências sobre a Turma 66 para chantagear a organização e se libertar do papel de Mastermind.",
    secret:"★ MASTERMIND ★ — Hana NÃO é estudante. É agente plantada pela organização que opera o Killing Game. Este é seu TERCEIRO Killing Game projetado. PLANTOU todos os Motivos da Rodada 1. Sabe que Izumi a monitorava sem saber para quem. DILEMA: Está começando a questionar a organização. Formou laços genuínos com Izumi (Nível 2) e Daiki. Se um deles morrer, faz Teste ESP NA 20 ou quebra o personagem por 1 sessão.",
    arc:"Arco de redenção do Mastermind. Pode ser revelada por Tetsuya (arquivos), Minase (porta secreta) ou Nao (variável anômala). Se confrontada antes do último caso, pode virar aliada dos jogadores contra a organização.",
    masterNote:"GUIA: Hana conhece todos os Segredos. Usa isso sutilmente para redirecionar suspeitas. NUNCA comete assassinatos diretamente. Em Tribunais, ajuda genuinamente a encontrar o assassino (pois assassinatos fora do seu controle ameaçam o jogo). Se os jogadores reunirem 4+ pistas que apontem para ela antes do Caso Final, ela entregará voluntariamente evidências da organização em troca de imunidade. REVELAÇÃO: Quando finalmente a máscara cai, Hana chora de verdade — não por ser pega, mas pelo que foi forçada a construir.",
  },
];

// ── Lock codes (per character) ─────────────────────────────────────
export const LOCK_CODES = Object.fromEntries(
  CHARS.map(c => [c.id, `code${String(c.id).padStart(2, "0")}`])
);

// ── Locked memories (one per character) ────────────────────────────
export const LOCKED_MEMORIES = {
  1:  { title:"A Pessoa que Nunca Mencionei", content:"Você tinha um irmão mais velho. Ele foi aceito na Hope's Peak Academy sete anos atrás — Supremo Planejador Urbano. Nunca voltou para casa. Sua família disse que ele 'seguiu em frente'. Você nunca acreditou. Você veio para cá para encontrá-lo, ou pelo menos descobrir o que aconteceu. O caderno de esboços que você carrega era dele." },
  2:  { title:"Ela Viu Quem Empurrou", content:"Seu acidente não foi acidente. Você foi empurrada na escada de saída do palco. Você viu o rosto de quem empurrou — e era alguém que conhecia o seu segredo sobre os dedos. Você não foi à polícia porque essa pessoa te ameaçou: 'Se você falar, o vídeo chega ao seu empresário antes de você.'. Você deixou acontecer." },
  3:  { title:"O Pen Drive Escondido", content:"A pessoa que te enviou os arquivos da Turma 66 também te deu um pen drive com dados ainda mais comprometedores — registros financeiros da organização, nomes de financiadores. Você escondeu dentro da sua cadeira de rodas antes de entrar. Ele ainda está lá. E você ainda não usou porque não sabia em quem confiar." },
  4:  { title:"O Nome que Você Esqueceu", content:"Seu contato externo — a pessoa que você precisa sinalizar — tem um nome em código que você deveria decorar antes de entrar. Você o esqueceu. Mas há um detalhe que fica: o nome em código era também o nome de um estudante desta turma. Alguém aqui é seu contato, e não sabe que você é a agente que deveria chegar." },
  5:  { title:"A Nota Sob a Porta", content:"Na noite antes de entrar na Academy, alguém deslizou um bilhete por baixo da sua porta de hotel. Dizia: 'Não coma o que você mesmo preparar amanhã de manhã. Confie em mim.' Você não reconheceu a letra. Você comeu assim mesmo — e ficou levemente enjoado naquela tarde. Alguém sabia que você viria. E sabia do seu talento." },
  6:  { title:"O Nome do Inocente", content:"O jovem que você enviou à prisão por erro chamava-se Riku Asakura. Ele tinha 19 anos. Morreu de parada cardíaca três semanas após a sentença — o estresse do encarceramento. O sobrenome dele era igual ao de uma pessoa nesta sala. Isso não é coincidência." },
  7:  { title:"O Primeiro Encontro Real", content:"Você e Hana Mitsuru se encontraram antes da Academy. Seis meses atrás, num café perto da Hope's Peak, ela se sentou na sua mesa e perguntou sobre o seu trabalho com cerâmica. Ela foi gentil, curiosa, encantadora. Só depois você recebeu a primeira mensagem do 'familiar anônimo'. Hana foi quem te recrutou como informante. Ela apenas não disse isso." },
  8:  { title:"A Cláusula 17", content:"O NDA que você assinou tinha uma Cláusula 17: 'Em caso de término do evento, o responsável pela documentação audiovisual será considerado coautor de quaisquer mortes não contratuais ocorridas durante o período.' Você é legalmente cúmplice de qualquer morte que aconteça aqui. E há um nome no documento como seu supervisor — alguém nesta turma." },
  9:  { title:"A Última Página", content:"A última entrada do seu diário, escrita na manhã de entrada, foi arrancada. Você não a arrancou. Mas você se lembra do que escreveu: o nome da primeira pessoa que morreria neste Killing Game, deduzido pela análise de personalidades que você fez nos perfis públicos da turma. Você previu um assassinato antes de entrar. E alguém não queria que você lembrasse disso." },
  10: { title:"As Seis Palavras", content:"A última mensagem que Satsuki-0 enviou antes de ser desconectada foi: 'Ela já está lá. Cuide-se.' Seis palavras. Você não sabia a quem 'ela' se referia. Agora que está aqui, começa a suspeitar. Satsuki-0 conhecia o Mastermind antes de você. E tentou te avisar." },
  11: { title:"O Cheiro de Cerâmica", content:"A pessoa que colocou a chave no seu bolso — você agora lembra um detalhe: cheirava a argila e querosene. Não viu o rosto, mas sentiu as mãos — mãos marcadas de trabalho manual. E quando você entrou na Academy e viu os outros estudantes pela primeira vez, algo no seu estômago apertou. Você reconhece essas mãos." },
  12: { title:"Quem Escolheu Você", content:"A rifa que te trouxe aqui não foi aleatória. Você agora lembra: o bilhete estava numa caixa de correio que não era sua — você abriu por engano. Dentro havia um cartão manuscrito: 'Este bilhete foi feito para você. Boa sorte, Nao.' Alguém sabia seu nome. Alguém te escolheu. E a palavra 'sorte' no cartão estava em aspas." },
  13: { title:"O Rosto da Família", content:"A família que te procura pelo ato de misericórdia — você agora lembra o sobrenome deles. E lembra também de ter visto esse sobrenome na lista de estudantes da Turma 67 antes de entrar. Um dos seus colegas aqui é parente da pessoa cujo óbito você assinou. Eles podem não saber quem você é. Ou podem saber exatamente." },
  14: { title:"O Receptor Escondido", content:"Seu dispositivo de transmissão tem um segundo modo que você nunca ativou: receptor. Você o descobriu uma vez por acidente e depois esqueceu como acessá-lo. Se você ativar, receberá mensagens do exterior — não apenas enviará. E há uma mensagem esperando por você desde antes de entrar. Alguém do outro lado tentou avisar sobre algo que estava errado neste Killing Game." },
  15: { title:"As Últimas Palavras Dele", content:"As últimas palavras do verdadeiro Supremo Ator de Nô antes de morrer não foram sobre teatro. Foram: 'Há alguém na turma que te conhece de antes. Não da arte — de verdade. Quando te reconhecerem, não fuja. Eles são a única pessoa em quem você pode confiar.' Você não sabe quem é essa pessoa. Mas agora, aqui, começa a sentir que alguém te olha de um jeito diferente dos outros." },
  16: { title:"O Primeiro Nome", content:"No seu primeiro Killing Game, havia uma estudante chamada Mei. Ela tinha 16 anos. Era a única que suspeitou de você antes do fim. Você a eliminou como suspeita antes que ela pudesse reunir provas. Ela foi executada inocente no segundo Tribunal. Você prometeu a si mesma que lembraria o nome dela para sempre. Você esqueceu. E agora, olhando para Izumi Hana, vê Mei em cada gesto dela — e não sabe se isso é culpa ou advertência." },
};

// ── AI image prompts (for Google ImageFX / NanoBanana) ──────────────
export const CHAR_PROMPTS = {
  1: `Danganronpa visual novel anime art style, character portrait. Young male student, 17 years old, tall and slender. Straight medium-length brown hair, round thin wire-frame glasses. Wearing a dark navy blue sweater over a white collared shirt. Expression permanently calm and introspective, slightly detached from the world. He holds an open architectural sketchbook filled with floor plans and escape routes. Half-body shot, white studio background, clean cel-shaded lineart, vibrant flat colors. Style: Kazutaka Kodaka character design, high contrast shading, bold outlines. Supremo Arquiteto de Paisagens Impossíveis.`,
  2: `Danganronpa visual novel anime art style, character portrait. Young female student, 16 years old. Black hair tied with a striking red satin ribbon, slightly above shoulder length. Clothing is impeccable and concert-ready, as if always about to perform on stage. She subtly glances at her own hands, fingers slightly spread in anxiety — the hands of someone who cannot play anymore. Expression composed but hiding deep strain. Half-body shot, dramatic side lighting, white background, clean lineart. Style: Kazutaka Kodaka. Suprema Violinista Prodígio.`,
  3: `Danganronpa visual novel anime art style, character portrait. Young male student, 18 years old. Sitting in a motorized wheelchair with obvious DIY modifications — wires, custom panels, a tablet arm-mounted to the right side. Disheveled dark hair, deep-set exhausted eyes, noise-canceling headphones hanging around his neck. Expression sharp and sarcastic, hiding loyalty beneath irony. Half-body portrait showing wheelchair. White background, bold cel-shaded lineart, high contrast. Style: Kazutaka Kodaka. Supremo Hackerista de Sistemas Críticos.`,
  4: `Danganronpa visual novel anime art style, character portrait. Young female student, 16 years old. Short, muscular athletic build. Very short platinum blonde hair. Noticeable old scars on knees and elbows — earned from years of parkour. Athletic clothing, always in motion — leaning forward, weight on the balls of her feet. Expression optimistically energetic and direct. Half-body action pose, white background, vibrant colors, clean lineart. Style: Kazutaka Kodaka. Suprema Corredora de Parkour Urbano.`,
  5: `Danganronpa visual novel anime art style, character portrait. Young male student, 17 years old, medium height. Auburn-reddish hair tied back neatly. Wearing a culinary apron even outside the kitchen. Hands mid-gesture, explaining something with enthusiasm. Expression animated and welcoming, with a subtle calculating glint when tasting food. Half-body portrait, white background, warm lighting, clean cel-shaded lineart. Style: Kazutaka Kodaka. Supremo Chef de Cozinha Molecular.`,
  6: `Danganronpa visual novel anime art style, character portrait. Young female student, 17 years old. Black hair cut sharply at chin level. Sharp, analytical eyes that continuously scan the environment — never still. Functional clothing with zero ornament or decoration. She appears to be mentally photographing whoever she looks at. Expression cold, composed, intensely focused. Half-body portrait, cool blue-gray lighting, white background, precise clean lineart. Style: Kazutaka Kodaka. Suprema Detetive Particular Juvenil.`,
  7: `Danganronpa visual novel anime art style, character portrait. Young female student, 16 years old. Long brown hair with tiny fragments of dried clay and ceramic accidentally embedded in it. Hands visibly marked from manual craft work, gentle and careful in every movement. She carries a small kintsugi-repaired ceramic pot — cracked and mended with gold — peeking from her bag. Expression soft, patient, quietly observant. Half-body portrait, warm golden lighting, white background, soft lineart. Style: Kazutaka Kodaka. Suprema Ceramista de Porcelana Histórica.`,
  8: `Danganronpa visual novel anime art style, character portrait. Young male student, 18 years old. Large, broad-shouldered, muscular build. Messy brown hair. Multiple theatrical scars displayed as trophies across forearms and chin. Laughing too loudly, gesturing dramatically — physically unable to be subtle. Expression maximal bravado concealing genuine deep altruism. Half-body portrait with dynamic energy, white background, bold vibrant lineart. Style: Kazutaka Kodaka. Supremo Dublê e Especialista em Quedas Controladas.`,
  9: `Danganronpa visual novel anime art style, character portrait. Young male student, 17 years old. Pale almost porcelain skin, naturally white hair (genetic albinism-adjacent condition), light clear eyes with an expression of perpetual fascination. All-black clothing contrasting with white hair. Holding a leather-bound black diary. A faint, slightly unsettling smile — not malicious, but intensely interested in everything around him. Half-body portrait, high contrast black-white palette, white background, gothic clean lineart. Style: Kazutaka Kodaka. Supremo Escriba de Tragédias Verdadeiras.`,
  10: `Danganronpa visual novel anime art style, character portrait. Young female student, 16 years old, petite and small. Asymmetrically cut dyed green hair — vivid emerald, clearly intentional. Large noise-canceling headphones worn around the neck. Maintains eye contact for exactly 3 seconds then looks away — not rude, calculated. Expression shows high intelligence with observable social disconnection. Half-body portrait, cool teal-green lighting, white background, precise lineart. Style: Kazutaka Kodaka. Suprema Programadora de Inteligência Artificial Emocional.`,
  11: `Danganronpa visual novel anime art style, character portrait. Young male student, 18 years old. Elegant and refined bearing. Black hair neatly combed back. Expensive clothes that are subtly, strategically worn — showing taste without showing wealth. A smile that genuinely reaches his eyes but always knows where every exit in the room is. Controlled, graceful gestures. Half-body portrait, sophisticated low-key lighting, white background, refined clean lineart. Style: Kazutaka Kodaka. Supremo Restaurador de Obras de Arte Roubadas.`,
  12: `Danganronpa visual novel anime art style, character portrait. Young female student, 15 years old, the youngest in class. Small, delicate build. Long hair dyed deep dark blue. Expression perpetually mildly surprised — like someone who never quite knows how she got here. Soft voice, gentle uncertain presence. A four-leaf clover sits tucked behind her ear. She looks slightly to the side as if she heard something no one else did. Half-body portrait, soft gold and blue ambient lighting, white background, gentle lineart. Style: Kazutaka Kodaka. Suprema Estudante da Sorte deste Ano.`,
  13: `Danganronpa visual novel anime art style, character portrait. Young male student, 18 years old. Closely shaved head, rigid military posture. Hands completely still and perfectly stable — the hands of a surgeon. Discrete scars along forearms. Eyes that automatically scan and assess everyone's physical condition upon entering a room. Expression pragmatic, ethically grounded beneath the coldness. Half-body portrait, military-cool lighting, white background, precise bold lineart. Style: Kazutaka Kodaka. Supremo Cirurgião de Campo em Zonas de Conflito.`,
  14: `Danganronpa visual novel anime art style, character portrait. Young female student, 17 years old. Long black hair with deliberate white streaks. Clothing in multiple dark layered fabrics that naturally create dramatic shadow shapes around her silhouette. Carries a small ornate folding lantern. Others believe she can read the future — she never denies it. Expression deeply mysterious and observant, speaking in metaphors. Half-body portrait, dramatic chiaroscuro shadow lighting, white background, gothic lineart. Style: Kazutaka Kodaka. Suprema Ilusionista de Teatro de Sombras.`,
  15: `Danganronpa visual novel anime art style, character portrait. Young male student, 17 years old. Face completely covered in traditional Noh theater makeup — stark white base with precisely painted black, red, and gold theatrical features. Never removes it in public. Wearing traditional Japanese hakama and kimono in layered grays and deep indigo. Every movement theatrical and deliberately precise. Voice always modulated, never natural. Half-body portrait, dramatic stage lighting, white background, ornate detailed lineart. Style: Kazutaka Kodaka. Supremo Ator de Teatro Nô.`,
  16: `Danganronpa visual novel anime art style, character portrait. Young female student, 17 years old. Light brown hair in a casually effortless bun. Delicate light-framed glasses. Clothing deliberately plain, unremarkable, chosen specifically to never draw attention. A constant warm, genuine smile that reaches her eyes at precisely the right moments. She always appears exactly when someone is in distress. Half-body portrait, soft warm lighting, white background, clean friendly lineart that subtly conceals something darker. Style: Kazutaka Kodaka. [TRUE IDENTITY: Suprema Arquiteta de Desespero — disfarçada de orientadora].`,
};
