export const CHAPTERS = [
  {id:"c1",icon:"⚔️",title:"Fundamentos",content:[
    {head:"O Jogo",text:"DANGANRONPA: O Julgamento Supremo é um RPG de mesa de suspense e dedução para 4–8 jogadores + 1 Mestre. Um grupo de até 16 estudantes é forçado a participar de um Killing Game conduzido por Monokuma. Para sobreviver: descubra o assassino nos Tribunais. Para fugir: acumule Esperança suficiente. Para vencer do jeito errado: cometa o assassinato perfeito."},
    {head:"Dado Monokuma",text:"Sempre que um jogador rolar um 6 natural em qualquer teste, o Mestre pode ativar um Evento Monokuma — uma complicação ou revelação dramática inesperada."},
    {head:"Esperança ☀️ vs. Desesperança 💀",table:[
      ["Recurso","Aumenta quando…"],
      ["☀️ Esperança","Tribunal bem-sucedido, laços de amizade, descobertas positivas"],
      ["💀 Desesperança","Assassinato ocorre, acusação errada, revelação de segredos sombrios"],
    ]},
  ]},
  {id:"c2",icon:"🎭",title:"Personagem",content:[
    {head:"Atributos Base (60 pts | Mín:5 | Máx:15)",table:[
      ["Atributo","Sigla","O que representa"],
      ["Esperança","ESP","Força de vontade, resistência mental, moral"],
      ["Inteligência","INT","Raciocínio, dedução, memória, percepção"],
      ["Furtividade","FUR","Discrição, movimentação silenciosa, dissimulação"],
      ["Persuasão","PER","Convencimento, carisma, intimidação, mentira"],
      ["Resistência","RES","Físico, aguenta pressão, stamina"],
      ["Sorte","SOR","Acaso favorável, achados inesperados"],
    ]},
    {head:"Derivados (calculados automaticamente)",table:[
      ["Derivado","Fórmula"],
      ["PV Máximo","RES × 3 + 10"],
      ["PS Máximo","ESP × 3 + 10"],
      ["Iniciativa","INT + SOR"],
      ["Defesa Passiva","RES ÷ 2 (arredonda p/ baixo)"],
      ["Limite Monocoins","SOR × 5"],
    ]},
    {head:"Laços de Amizade (Nível 0–5)",table:[
      ["Nível","Nome","Benefício"],
      ["0","Desconhecidos","Nenhum"],
      ["1","Conhecidos","+1 em Persuasão com essa pessoa"],
      ["2","Amigos","Pode pedir 1 favor por sessão"],
      ["3","Amigos Próximos","+2 em testes para proteger/ajudar"],
      ["4","Confiança Plena","Pode compartilhar Segredo sem penalidade"],
      ["5","Vínculo Supremo","Habilidade especial co-desenvolvida com o Mestre"],
    ]},
  ]},
  {id:"c3",icon:"🎲",title:"Testes",content:[
    {head:"Como Fazer um Teste",text:"1. Role 1d20 → 2. Some o valor do Atributo relevante → 3. Compare ao Número Alvo (NA) definido pelo Mestre."},
    {head:"Resultados",table:[
      ["Resultado","Efeito"],
      ["Total ≥ NA + 5","Sucesso Crítico — resultado excepcional, bônus narrativo"],
      ["Total ≥ NA","Sucesso — ação bem-sucedida"],
      ["Total = NA−1 ou NA−2","Sucesso Parcial — funciona, mas com custo ou complicação"],
      ["Total < NA−2","Falha — ação falha, pode ter consequência"],
      ["1 natural","Falha Catastrófica — algo vai muito errado"],
    ]},
    {head:"Números Alvo de Referência",table:[
      ["Dificuldade","NA","Exemplo"],
      ["Fácil","10","Notar algo óbvio, mentira simples"],
      ["Médio","15","Encontrar pista escondida, convencer alguém incerto"],
      ["Difícil","20","Investigar cena apagada, enganar alguém desconfiado"],
      ["Supremo","25","Descoberta brilhante, manipulação perfeita"],
      ["Quase Impossível","30","Feito digno de um Supremo lendário"],
    ]},
    {head:"Vantagem e Desvantagem",text:"Vantagem: Role 2d20, use o maior. Concedida por preparação, equipamentos, laços de amizade.\nDesvantagem: Role 2d20, use o menor. Concedida por trauma, ferimento, falta de informação.\nTestes Opostos: Ambos rolam 1d20 + atributo. Vence o maior total. Empate: vence o Defensor."},
  ]},
  {id:"c4",icon:"🗺️",title:"Fases do Jogo",content:[
    {head:"Estrutura de uma Rodada",text:"[1] VIDA COTIDIANA\n↓ (Monokuma entrega Motivo)\n[2] FREE TIME / TENSÃO\n↓ (assassinato acontece OU não)\n[3] DESCOBERTA DO CORPO\n↓\n[4] INVESTIGAÇÃO (tempo limitado)\n↓\n[5] TRIBUNAL DE CLASSE\n↓ (execução OU sobrevivência)"},
    {head:"Motivos de Monokuma (d8)",table:[
      ["d8","Motivo"],
      ["1","Segredo Revelado — Monokuma vai expor o segredo de alguém"],
      ["2","Memória Apagada — Quer recuperar memória? Mate alguém"],
      ["3","Chantagem — Fotos/vídeos comprometedores enviados a familiares"],
      ["4","Dívida de Esperança — Se ninguém matar em 72h, alguém morre aleatório"],
      ["5","Recompensa — O assassino ganha um item lendário"],
      ["6","Ameaça Direta — Alguém recebe mensagem: 'mate X ou eu o mato'"],
      ["7","Rivalidade — Dois estudantes têm objetivos incompatíveis"],
      ["8","Motivo do Mestre — Personalizado"],
    ]},
    {head:"Free Time — Ações (2 por período)",table:[
      ["Ação","Custo","Efeito"],
      ["Conversar","Grátis","Testa Laço com outro estudante; +1 de Laço em Sucesso"],
      ["Dar Presente","1–3 Monocoins","+1 ou +2 de Laço, dependendo do presente"],
      ["Treinar","Grátis","+1 temporário em um Atributo até o próximo Tribunal"],
      ["Explorar","Grátis","Descobre um novo cômodo/área do mapa"],
      ["Planejar Crime","Grátis (secreto)","Elabora etapas do assassinato com o Mestre"],
      ["Descansar","Grátis","Recupera 1d6 PS"],
    ]},
  ]},
  {id:"c5",icon:"🔪",title:"Assassinato",content:[
    {head:"Etapas do Assassinato",text:"PLANEJAR (alvo + método + local + janela de tempo + álibi) → EXECUTAR (testes conforme o método) → COBRIR (até 3 ações de cobertura)"},
    {head:"Tipos de Execução",table:[
      ["Método","Teste","Detalhes"],
      ["Confronto Direto","RES vs RES (Oposto)","Se vencer: sucesso. Se perder: vítima escapa e pode gritar."],
      ["Veneno/Armadilha","INT (NA 15–20) + FUR (NA 15)","Vítima faz Teste SOR para notar algo errado"],
      ["Emboscada","FUR vs INT (Oposto)","Se vencer: ataque surpresa, vítima não resiste na rodada inicial"],
    ]},
    {head:"Ações de Cobertura (máx. 3)",table:[
      ["Ação","Teste","Efeito"],
      ["Apagar Rastros de Sangue","FUR NA 18","Remove 1 Pista Física da cena"],
      ["Criar Pista Falsa","INT NA 20","Adiciona 1 Pista Enganosa à cena"],
      ["Forjar Álibi","PER NA 18","Cria testemunho fabricado com NPC"],
      ["Esconder Arma","FUR NA 15","Arma não aparece na investigação inicial"],
      ["Mover o Corpo","RES NA 15","Corpo encontrado em local diferente do crime"],
    ]},
  ]},
  {id:"c6",icon:"🔍",title:"Investigação",content:[
    {head:"Zonas de Investigação",text:"O Mestre divide o mapa em Zonas. Cada zona pode ser investigada uma vez por jogador. Declare a zona → Teste de INT (NA 12–18) → encontre pistas conforme o resultado."},
    {head:"Resultado da Investigação",table:[
      ["Resultado do Teste","Pistas Encontradas"],
      ["Falha","Nenhuma pista, ou pista falsa plantada pelo assassino"],
      ["Sucesso Parcial","1 pista menor (pode ser ambígua)"],
      ["Sucesso","1–2 pistas relevantes"],
      ["Sucesso Crítico","2–3 pistas, incluindo uma pista oculta"],
    ]},
    {head:"Tipos de Pistas",table:[
      ["Tipo","Cor","Descrição"],
      ["🔵 Física","Azul","Objeto tangível (faca, copo, tecido)"],
      ["🟡 Temporal","Amarelo","Indica horário (alarme, câmera, cardápio)"],
      ["🟢 Testemunhal","Verde","Relato de NPC ou outro estudante"],
      ["🔴 Emocional","Vermelho","Pista psicológica (carta, diário, motivação)"],
      ["⚫ Falsa","Preto","Plantada pelo assassino (o jogador não sabe)"],
    ]},
    {head:"Força das Balas de Verdade",table:[
      ["Força","Tipo","Efeito no Tribunal"],
      ["⭐","Pista menor, ambígua","Levanta dúvida"],
      ["⭐⭐","Pista direta, circunstancial","Força uma explicação"],
      ["⭐⭐⭐","Pista forte, específica","Destrói um argumento"],
      ["⭐⭐⭐⭐","Prova conclusiva","Pode encerrar um debate"],
    ]},
  ]},
  {id:"c7",icon:"⚖️",title:"Tribunal",content:[
    {head:"Estrutura do Tribunal",text:"[1] ABERTURA (suspeitas secretas) → [2] DEBATE LIVRE (15 min reais) → [3] NONSTOP DEBATE (Balas de Verdade) → [4] ACUSAÇÃO FINAL → [5] VOTAÇÃO"},
    {head:"Nonstop Debate — Regras",text:"1. O Mestre apresenta 4–6 Declarações — afirmações dos suspeitos sobre o crime.\n2. Cada Declaração tem uma Fraqueza.\n3. Em ordem de Iniciativa: atirar Bala, apoiar Declaração ou passar.\n\nTiro de Bala: 'Uso [Bala] contra [Declaração X]' → Teste INT (NA = 10 + Força × 3)\nSucesso: Declaração destruída. Falha: Bala desperdiçada."},
    {head:"Resultado da Votação",table:[
      ["Cenário","Resultado"],
      ["Maioria vota ☝ e está CERTA","Assassino executado. +3 Esperança. Próxima fase começa."],
      ["Maioria vota ☝ mas está ERRADA","Assassino escapa! Monokuma executa inocente aleatório. −5 Esperança"],
      ["Empate","Monokuma escolhe aleatoriamente um suspeito para executar"],
      ["Maioria vota 👎","Ninguém executado. −2 Esperança. Assassino fica livre para matar novamente."],
    ]},
    {head:"Bônus de Performance (Monocoins)",table:[
      ["Conquista","Monocoins"],
      ["Fez a Acusação Final correta","+5"],
      ["Destruiu 3+ Declarações com Balas","+3"],
      ["Mentiu convincentemente por 2+ rodadas (assassino)","+3"],
      ["Descobriu a Pista Decisiva","+4"],
      ["Não perdeu nenhuma Bala durante o debate","+2"],
      ["Mudou o rumo do Tribunal com 1 argumento","+2"],
    ]},
  ]},
  {id:"c8",icon:"🏆",title:"Vitória e Derrota",content:[
    {head:"Vitórias Individuais",table:[
      ["Condição","Tipo de Vitória"],
      ["Sobreviver até o fim do Killing Game","Vitória de Sobrevivência"],
      ["Cometer um assassinato perfeito e fugir","Vitória do Assassino"],
      ["Descobrir o assassino em todos os Tribunais","Vitória do Detetive"],
      ["Acumular 30+ Monocoins","Vitória de Fortuna"],
    ]},
    {head:"Vitória Coletiva",text:"O grupo pode vencer coletivamente se:\n• A Esperança global atingir 50\n• Descobrirem o 'segredo do Killing Game' (gatilho narrativo do Mestre)\n• Confrontarem Monokuma com evidências de sua fraqueza"},
    {head:"Derrota Coletiva",text:"O grupo perde se:\n• Restar apenas 1 estudante vivo (sem ter descoberto o segredo)\n• A Desesperança global atingir 50\n• Um assassino escapar impune 3 vezes seguidas"},
  ]},
];
